# Generated by Django 6.0.2 on 2026-03-15 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('enabled', models.BooleanField(default=False)),
                ('session_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], default='both', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Schedule Day',
                'verbose_name_plural': 'Weekly Schedule Days',
                'db_table': 'scheduling_weekly_schedule_day',
                'ordering': ['day_of_week'],
                'unique_together': {('user', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scheduling.weeklyscheduleday')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'db_table': 'scheduling_time_slot',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='DateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Date Override',
                'verbose_name_plural': 'Date Overrides',
                'db_table': 'scheduling_date_override',
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
