# Generated by Django 6.0.2 on 2026-03-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_booking_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingGroupProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Booking Request',
                'verbose_name_plural': 'Booking Requests (Grouped)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.booking',),
        ),
    ]
