# Generated by Django 6.0.2 on 2026-03-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_booking_group_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted – Awaiting Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('completed', 'Completed')], default='pending', max_length=15),
        ),
    ]
