# Generated by ChatGPT on 2026-04-01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('accepted', 'Accepted – Awaiting Payment'),
                    ('confirmed', 'Confirmed'),
                    ('cancelled', 'Cancelled'),
                    ('refund_pending', 'Refund Pending'),
                    ('refunded', 'Refunded'),
                    ('completed', 'Completed'),
                    ('in_progress', 'In Progress'),
                    ('disputed', 'Disputed'),
                    ('no_show_client', 'No Show (Client)'),
                    ('session_was_taken_but_not_end_by_client', 'Session Taken But End Not Confirmed By Client'),
                    ('missed', 'Missed'),
                ],
                default='pending',
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name='booking',
            name='session_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='session_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SessionVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('start', 'Start Session Request'), ('end', 'End Session Request')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('response_reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='scheduling.booking')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_verification_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_verification_requests_responded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Verification Request',
                'verbose_name_plural': 'Session Verification Requests',
                'db_table': 'scheduling_session_verification_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sessionverificationrequest',
            index=models.Index(fields=['booking', 'request_type', 'status'], name='scheduling_s_booking_4a62a2_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionverificationrequest',
            index=models.Index(fields=['expires_at', 'status'], name='scheduling_s_expires_8cf8b9_idx'),
        ),
    ]
