# Generated by Django 6.0.2 on 2026-04-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_session_verification_request'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sessionverificationrequest',
            new_name='scheduling__booking_a287a0_idx',
            old_name='scheduling_s_booking_4a62a2_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionverificationrequest',
            new_name='scheduling__expires_e77458_idx',
            old_name='scheduling_s_expires_8cf8b9_idx',
        ),
    ]
