# Generated by Django 6.0.2 on 2026-04-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_booking_booking_created_idx_booking_booking_date_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='bkg_created_idx',
            old_name='booking_created_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bkg_date_idx',
            old_name='booking_date_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bkg_status_idx',
            old_name='booking_status_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bkg_status_cr_idx',
            old_name='booking_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bkg_trainer_cr_idx',
            old_name='booking_trainer_created_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bkg_client_cr_idx',
            old_name='booking_client_created_idx',
        ),
    ]
