# Generated by Django 6.0.2 on 2026-02-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='userbase',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userbase',
            name='contact_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userbase',
            name='expertise_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userbase',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userbase',
            name='is_trainer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbase',
            name='pricing_per_session',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userbase',
            name='session_type',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userbase',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
