# Generated by Django 6.0.2 on 2026-02-26 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_userbase_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='id_proof',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbase',
            name='id_proof_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TrainerCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('image', models.BinaryField()),
                ('content_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trainer Certification',
                'verbose_name_plural': 'Trainer Certifications',
                'db_table': 'system_trainer_certification',
            },
        ),
    ]
