# Generated by Django 6.0.2 on 2026-02-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_userbase_id_proof_userbase_id_proof_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='is_admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
