# Generated by Django 6.0.2 on 2026-02-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_userbase_is_admin_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
