# Generated by Django 6.0.2 on 2026-02-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_userbase_first_name_alter_userbase_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
