# Generated by Django 6.0.2 on 2026-03-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_userbase_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('re_verification_required', 'Re-verification Required')], default='pending', max_length=30),
        ),
    ]
