# Generated by Django 6.0.2 on 2026-03-12 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_userbase_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('re_verification_required', 'Re-verification Required'), ('reverification_rejected', 'Re-verification Rejected')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='TrainerProfileChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('id_proof_updated', 'ID Proof Updated'), ('certification_added', 'Certification Added'), ('certification_deleted', 'Certification Deleted'), ('profile_fields_updated', 'Profile Fields Updated')], max_length=50)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trainer Change Log',
                'verbose_name_plural': 'Trainer Change Logs',
                'db_table': 'system_trainer_change_log',
                'ordering': ['-changed_at'],
            },
        ),
    ]
