# Generated by Django 6.0.2 on 2026-03-12 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_trainer_profile_change_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('content_type', models.CharField(max_length=100)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trainer Gallery Image',
                'verbose_name_plural': 'Trainer Gallery Images',
                'db_table': 'system_trainer_gallery_image',
                'ordering': ['-created_at'],
            },
        ),
    ]
