# Generated by Django 6.0.2 on 2026-03-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_trainer_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainergalleryimage',
            name='collection_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
