# Generated by Django 6.0.2 on 2026-04-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('system', '0011_trainer_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userbase',
            index=models.Index(fields=['-created_at'], name='userbase_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userbase',
            index=models.Index(fields=['is_trainer'], name='userbase_is_trainer_idx'),
        ),
        migrations.AddIndex(
            model_name='userbase',
            index=models.Index(fields=['is_trainer', '-created_at'], name='userbase_trainer_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userbase',
            index=models.Index(fields=['is_admin_approved'], name='userbase_approved_idx'),
        ),
        migrations.AddIndex(
            model_name='userbase',
            index=models.Index(fields=['verification_status'], name='userbase_verification_idx'),
        ),
    ]
