# Generated by Django 6.0.2 on 2026-04-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_userbase_userbase_created_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userbase',
            new_name='usr_created_idx',
            old_name='userbase_created_idx',
        ),
        migrations.RenameIndex(
            model_name='userbase',
            new_name='usr_is_trainer_idx',
            old_name='userbase_is_trainer_idx',
        ),
        migrations.RenameIndex(
            model_name='userbase',
            new_name='usr_trainer_cr_idx',
            old_name='userbase_trainer_created_idx',
        ),
        migrations.RenameIndex(
            model_name='userbase',
            new_name='usr_approved_idx',
            old_name='userbase_approved_idx',
        ),
        migrations.RenameIndex(
            model_name='userbase',
            new_name='usr_verif_idx',
            old_name='userbase_verification_idx',
        ),
    ]
