# Generated by Django 6.0.2 on 2026-03-25 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0007_booking_group_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhaltiPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pidx', models.CharField(max_length=255, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('amount', models.PositiveBigIntegerField(help_text='Amount in paisa (Rs. 1 = 100 paisa)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('khalti_response', models.JSONField(blank=True, default=dict)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='scheduling.booking')),
            ],
            options={
                'verbose_name': 'Khalti Payment',
                'verbose_name_plural': 'Khalti Payments',
                'db_table': 'payment_khalti_payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
