# Generated by Django 6.0.2 on 2026-03-25 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('scheduling', '0008_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='khaltipayment',
            name='platform_fee',
            field=models.PositiveBigIntegerField(default=0, help_text='5% platform fee in paisa (auto-set)'),
        ),
        migrations.AlterField(
            model_name='khaltipayment',
            name='amount',
            field=models.PositiveBigIntegerField(help_text='Total amount in paisa'),
        ),
        migrations.AlterField(
            model_name='khaltipayment',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='initiated', max_length=20),
        ),
        migrations.CreateModel(
            name='ClientRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveBigIntegerField(help_text='Refund amount in paisa (70% of total)')),
                ('status', models.CharField(choices=[('pending', 'Pending Refund'), ('processed', 'Processed')], default='pending', max_length=15)),
                ('refund_reference', models.CharField(blank=True, help_text='Khalti refund txn ID or bank ref', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_refund', to='payment.khaltipayment')),
            ],
            options={
                'verbose_name': 'Client Refund',
                'verbose_name_plural': 'Client Refunds',
                'db_table': 'payment_client_refund',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_type', models.CharField(choices=[('advance_25', 'Advance 25%'), ('final_70', 'Final 70%')], max_length=15)),
                ('amount', models.PositiveBigIntegerField(help_text='Amount in paisa')),
                ('status', models.CharField(choices=[('pending', 'Pending Transfer'), ('on_hold', 'On Hold'), ('transferred', 'Transferred'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('transfer_reference', models.CharField(blank=True, help_text='Khalti P2P txn ID or bank ref', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_payouts', to='scheduling.booking')),
            ],
            options={
                'verbose_name': 'Trainer Payout',
                'verbose_name_plural': 'Trainer Payouts',
                'db_table': 'payment_trainer_payout',
                'ordering': ['-created_at'],
            },
        ),
    ]
