# Generated by Django 6.0.2 on 2026-04-01

import django.db.models.deletion
import payment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_khaltipayment_platform_fee_and_more'),
        ('scheduling', '0008_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_group_id', models.CharField(default=payment.models._payment_group_id, editable=False, max_length=40, unique=True)),
                ('pidx', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('total_amount', models.PositiveBigIntegerField(help_text='Total amount in paisa across all selected bookings')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='initiated', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('khalti_response', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Group',
                'verbose_name_plural': 'Payment Groups',
                'db_table': 'payment_payment_group',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGroupBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveBigIntegerField(default=0, help_text='Per-booking amount in paisa')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_group_links', to='scheduling.booking')),
                ('payment_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_links', to='payment.paymentgroup')),
            ],
            options={
                'verbose_name': 'Payment Group Booking',
                'verbose_name_plural': 'Payment Group Bookings',
                'db_table': 'payment_payment_group_booking',
                'ordering': ['-created_at'],
                'unique_together': {('payment_group', 'booking')},
            },
        ),
        migrations.AddField(
            model_name='paymentgroup',
            name='bookings',
            field=models.ManyToManyField(related_name='payment_groups', through='payment.PaymentGroupBooking', to='scheduling.booking'),
        ),
    ]
