# Generated by Django 6.0.2 on 2026-04-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentgroup_and_paymentgroupbooking'),
        ('scheduling', '0011_booking_booking_created_idx_booking_booking_date_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientrefund',
            index=models.Index(fields=['-created_at'], name='payment_refund_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clientrefund',
            index=models.Index(fields=['status'], name='payment_refund_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clientrefund',
            index=models.Index(fields=['processed_at'], name='payment_refund_processed_idx'),
        ),
        migrations.AddIndex(
            model_name='khaltipayment',
            index=models.Index(fields=['-created_at'], name='payment_khalti_created_idx'),
        ),
        migrations.AddIndex(
            model_name='khaltipayment',
            index=models.Index(fields=['status'], name='payment_khalti_status_idx'),
        ),
        migrations.AddIndex(
            model_name='khaltipayment',
            index=models.Index(fields=['status', '-created_at'], name='payment_khalti_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerpayout',
            index=models.Index(fields=['-created_at'], name='payment_payout_created_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerpayout',
            index=models.Index(fields=['status'], name='payment_payout_status_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerpayout',
            index=models.Index(fields=['transferred_at'], name='payment_payout_transferred_idx'),
        ),
    ]
