# Generated by Django 6.0.2 on 2026-04-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_clientrefund_payment_refund_created_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientrefund',
            new_name='pmt_refund_created_idx',
            old_name='payment_refund_created_idx',
        ),
        migrations.RenameIndex(
            model_name='clientrefund',
            new_name='pmt_refund_status_idx',
            old_name='payment_refund_status_idx',
        ),
        migrations.RenameIndex(
            model_name='clientrefund',
            new_name='pmt_refund_proc_idx',
            old_name='payment_refund_processed_idx',
        ),
        migrations.RenameIndex(
            model_name='khaltipayment',
            new_name='pmt_khalti_created_idx',
            old_name='payment_khalti_created_idx',
        ),
        migrations.RenameIndex(
            model_name='khaltipayment',
            new_name='pmt_khalti_status_idx',
            old_name='payment_khalti_status_idx',
        ),
        migrations.RenameIndex(
            model_name='khaltipayment',
            new_name='pmt_khalti_st_cr_idx',
            old_name='payment_khalti_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='trainerpayout',
            new_name='pmt_payout_created_idx',
            old_name='payment_payout_created_idx',
        ),
        migrations.RenameIndex(
            model_name='trainerpayout',
            new_name='pmt_payout_status_idx',
            old_name='payment_payout_status_idx',
        ),
        migrations.RenameIndex(
            model_name='trainerpayout',
            new_name='pmt_payout_transf_idx',
            old_name='payment_payout_transferred_idx',
        ),
    ]
